import Head from "next/head";
import Script from "next/script";
import type { Metadata } from "next";

import localfont from "next/font/local";
import { ReduxProvider } from "@/redux/reduxProvider";
import NoSSRWrapper from "./components/noSSRWrapper/noSSRWrapper";

// tailwind
import "tailwindcss/tailwind.css";

/* Core CSS required for Ionic components to work properly */
import "@ionic/react/css/core.css";

/* Basic CSS for apps built with Ionic */
import "@ionic/react/css/normalize.css";
// import "@ionic/react/css/structure.css";
import "@ionic/react/css/typography.css";

/* Optional CSS utils that can be commented out */
import "@ionic/react/css/padding.css";
import "@ionic/react/css/float-elements.css";
import "@ionic/react/css/text-alignment.css";
import "@ionic/react/css/text-transformation.css";
import "@ionic/react/css/flex-utils.css";
import "@ionic/react/css/display.css";

import "../../styles/globals.css";
import "../../styles/variables.css";
// -----------------------------------------------------------------

// custom font
const interFont = localfont({
  src: [
    {
      path: "../../public/fonts/Inter-Regular.ttf",
      weight: "500",
    },
  ],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Youapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, viewport-fit=cover"
        ></meta>
      </Head>
      <body className={`${interFont.variable}`}>
        <NoSSRWrapper>
          <ReduxProvider>{children}</ReduxProvider>
        </NoSSRWrapper>
        <Script
          type="module"
          src="https://unpkg.com/ionicons@5.2.3/dist/ionicons/ionicons.esm.js"
        ></Script>
        <Script
          noModule={true}
          src="https://unpkg.com/ionicons@5.2.3/dist/ionicons/ionicons.js"
        ></Script>
      </body>
    </html>
  );
}
